name: Docker Player

on:
  pull_request:
    types: [labeled]
    
jobs:
  action-player:
     runs-on: ubuntu-latest
     container: 
        image: hashicorp/terraform
        env:
          WORKDIR: /workdir
        volumes:
          - /workdir:./.github/actions/hello-tf
     steps:
        - uses: actions/checkout@v2
        
        - name: hello-terraform
          uses: ./.github/actions/hello-tf
          
        - name: init
          run: init
